bracketSpacing: true
endOfLine: "auto"
printWidth: 80
proseWrap: "always"
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false

overrides:
  - files: "*.md"
    options:
      printWidth: 120
  - files: ["*.d.ts", "*.ts", "*.tsx"]
    options:
      importOrder:
        - "^@"
        - "<TS_TYPES>"
        - "<THIRD_PARTY_MODULES>"
        - "<THIRD_PARTY_TS_TYPES>"
        - "^../generated|^../../src/generated"
        - "^[./]"
      importOrderSeparation: false
      importOrderSortSpecifiers: true
  - files: ["*.yml", "*.yaml", "*.graphql"]
    options:
      bracketSpacing: false
      printWidth: 120
