name: sablier-v2-merkle
unordered_multichain_mode: true
contracts:
  - name: MerkleLockupFactoryV21
    handler: src/mappings/index.ts
    events:
      - event:
          CreateMerkleStreamerLL(address merkleStreamer, address indexed admin, address indexed lockupLinear, address
          indexed asset, bytes32 merkleRoot, uint40 expiration, (uint40, uint40) streamDurations, bool cancelable, bool
          transferable, string ipfsCID, uint256 aggregateAmount, uint256 recipientsCount)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Factory
          - name: Watcher
  - name: MerkleLockupFactoryV22
    handler: src/mappings/index.ts
    events:
      - event: CreateMerkleLL(address indexed merkleLL, (address, bool, uint40, address, string, bytes32, string, bool) baseParams, address lockupLinear, (uint40, uint40) streamDurations, uint256 aggregateAmount, uint256 recipientCount)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Factory
          - name: Watcher
      - event: CreateMerkleLT(address indexed merkleLT, (address, bool, uint40, address, string, bytes32, string, bool) baseParams, address lockupTranched, (uint64, uint40)[] tranchesWithPercentages, uint256 totalDuration, uint256 aggregateAmount,uint256 recipientCount)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Factory
          - name: Watcher
          - name: Tranche
  - name: MerkleLockupV21
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount, uint256 indexed streamId)
        requiredEntities:
          - name: Activity
          - name: Campaign
          - name: Watcher
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
        requiredEntities:
          - name: Campaign
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Asset
          - name: Campaign
          - name: Watcher
  - name: MerkleLockupV22
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount, uint256 indexed streamId)
        requiredEntities:
          - name: Activity
          - name: Campaign
          - name: Watcher
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
        requiredEntities:
          - name: Campaign
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Asset
          - name: Campaign
          - name: Watcher
networks:
  - id: 42161
    start_block: 161026550
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x237400ef5a41886a75b0e036228221df075b3b80
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 43114
    start_block: 41023950
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x4849e797d7aab20fcc8f807efafdfff98a83412e
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 8453
    start_block: 8026890
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x5545c8e7c3e1f74adc98e518f2e8d23a002c4412
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 81457
    start_block: 244700
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x92fc05e49c27884d554d98a5c01ff0894a9dc29a
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 56
    start_block: 34438430
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x434d73465aac4125d204a6637eb6c579d8d69f48
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 100
    start_block: 31491790
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x777f66477ff83ababadf39a3f22a8cc3aee43765
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 1
    start_block: 17615650
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x1a272b596b10f02931480bc7a3617db4a8d154e3
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 10
    start_block: 113621900
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x044ec80fbec40f0ee7e7b3856828170971796c19
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 137
    start_block: 51245830
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0xf4906225e783fb8977410bdbfb960cabed6c2ef4
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 534352
    start_block: 1675330
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0xb3ade5463000e6c0d376e7d7570f372ebf98bdaf
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 11155111
    start_block: 4904890
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0xbacc1d151a78eed71d504f701c25e8739dc0262d
      - name: MerkleLockupFactoryV22
        address:
          - 0x56e9180a8d2c35c99f2f8a1a5ab8abe79e876e8c
      - name: MerkleLockupV21
      - name: MerkleLockupV22
  - id: 324
    start_block: 33148900
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x46de683d20c3575a0381ffd66c10ab6836390140
      - name: MerkleLockupV21
      - name: MerkleLockupV22
