# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sablier-v2-merkle
unordered_multichain_mode: true
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
contracts:
  - name: MerkleLockupFactoryV21
    handler: src/mappings/index.ts
    events:
      - event:
          CreateMerkleStreamerLL(address merkleStreamer, address indexed admin, address indexed lockupLinear, address
          indexed asset, bytes32 merkleRoot, uint40 expiration, (uint40, uint40) streamDurations, bool cancelable, bool
          transferable, string ipfsCID, uint256 aggregateAmount, uint256 recipientsCount)
  - name: MerkleLockupFactoryV22
    handler: src/mappings/index.ts
    events:
      - event: CreateMerkleLL(address indexed merkleLL, (address, bool, uint40, address, string, bytes32, string, bool) baseParams, address lockupLinear, (uint40, uint40) streamDurations, uint256 aggregateAmount, uint256 recipientCount)
      - event: CreateMerkleLT(address indexed merkleLT, (address, bool, uint40, address, string, bytes32, string, bool) baseParams, address lockupTranched, (uint64, uint40)[] tranchesWithPercentages, uint256 totalDuration, uint256 aggregateAmount,uint256 recipientCount)
  - name: MerkleLockupV21
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount, uint256 indexed streamId)
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
  - name: MerkleLockupV22
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount, uint256 indexed streamId)
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
networks:
  - id: 11155111
    start_block: 4904890
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0xbacc1d151a78eed71d504f701c25e8739dc0262d
      - name: MerkleLockupFactoryV22
        address:
          - 0x56e9180a8d2c35c99f2f8a1a5ab8abe79e876e8c
      - name: MerkleLockupV21
      - name: MerkleLockupV22
