name: sablier-v2-protocol
contracts:
  - name: LockupV20
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        requiredEntities:
          - name: Watcher
      - event:
          CancelLockupStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint128
          senderAmount, uint128 recipientAmount)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint40,uint40,uint40) range,
          address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Watcher
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint128,uint64,uint40)[] segments,
          (uint40,uint40) range, address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Watcher
      - event: RenounceLockupStream(uint256 indexed streamId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Contract
      - event: WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, uint128 amount)
        requiredEntities:
          - name: Stream
          - name: Watcher
networks:
  - id: 42161
    start_block: 107509950
    contracts:
      - name: LockupV20
        address:
          - 0x197d655f3be03903fd25e7828c3534504bfe525e
          - 0xa9efbef1a35ff80041f567391bdc9813b2d50197
  - id: 11155111
    start_block: 4067889
    contracts:
      - name: LockupV20
        address:
          - 0xd4300c5bc0b9e27c73ebabdc747ba990b1b570db
          - 0x421e1e7a53ff360f70a2d02037ee394fa474e035
