name: sablier-v2-protocol
unordered_multichain_mode: true
contracts:
  - name: LockupV20
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        requiredEntities:
          - name: Watcher
      - event:
          CancelLockupStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint128
          senderAmount, uint128 recipientAmount)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint40,uint40,uint40) range,
          address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Watcher
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint128,uint64,uint40)[] segments,
          (uint40,uint40) range, address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Segment
          - name: Watcher
      - event: RenounceLockupStream(uint256 indexed streamId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Contract
          - name: Watcher
      - event: WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, uint128 amount)
        requiredEntities:
          - name: Stream
          - name: Watcher
  - name: LockupV21
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        requiredEntities:
          - name: Watcher
      - event:
          CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed asset,
          uint128 senderAmount, uint128 recipientAmount)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint40,uint40,uint40) range, address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Watcher
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint64,uint40)[] segments, (uint40,uint40) range, address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Segment
          - name: Watcher
      - event: RenounceLockupStream(uint256 indexed streamId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Contract
          - name: Watcher
      - event:
          WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed asset, uint128 amount)
        requiredEntities:
          - name: Stream
          - name: Watcher
  - name: LockupV22
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        requiredEntities:
          - name: Watcher
      - event:
          CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed asset,
          uint128 senderAmount, uint128 recipientAmount)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint40,uint40,uint40) timestamps, address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Watcher
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint64,uint40)[] segments, (uint40,uint40) timestamps, address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Segment
          - name: Watcher
      - event:
          CreateLockupTranchedStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint40)[] tranches, (uint40,uint40) timestamps, address broker)
        isAsync: true
        requiredEntities:
          - name: Asset
          - name: Batch
          - name: Batcher
          - name: Contract
          - name: Tranche
          - name: Watcher
      - event: RenounceLockupStream(uint256 indexed streamId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        requiredEntities:
          - name: Stream
          - name: Watcher
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
        requiredEntities:
          - name: Contract
          - name: Watcher
      - event:
          WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed asset, uint128 amount)
        requiredEntities:
          - name: Stream
          - name: Watcher
networks:
  - id: 42161
    start_block: 161026550
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 43114
    start_block: 41023950
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 8453
    start_block: 8026890
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 81457
    start_block: 244700
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 56
    start_block: 34438430
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 100
    start_block: 31491790
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 1
    start_block: 17615650
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 10
    start_block: 113621900
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 137
    start_block: 51245830
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 534352
    start_block: 1675330
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 11155111
    start_block: 4904890
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
  - id: 324
    start_block: 33148900
    contracts:
      - name: LockupV20
        address:
      - name: LockupV21
        address:
      - name: LockupV22
        address:
